---

# trying to install nginx and update the cache in the same step fails on first run
- name: Update cache as a separate step
  apt:
    update_cache: yes
# TODO add time constraint

- name: Upgrade all packages
  apt:
    upgrade: safe
    force_apt_get: yes
  async: 3600
  poll: 30

- name: Perform autoclean
  apt:
    autoclean: yes
    force_apt_get: yes

- name: Perform autoremove
  apt:
    autoremove: yes
    force_apt_get: yes

- name: Install vim
  apt:
   name: vim
   state: present

- name: Install git
  apt:
   name: git
   state: present

- name: Install nodejs
  apt:
   name: nodejs
   state: present

- name: Install npm
  apt:
   name: npm
   state: present
  async: 3600
  poll: 30

- name: Install express
  npm:
    name: express
    global: yes
    state: present

- name: Install latest nginx
  apt:
    name: nginx
    state: latest
  notify:
  - Restart nginx

- name: Install certbot as snap
  snap:
    name: certbot
    classic: yes

- name: Prepare certbot command
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Ensure nginx started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
