---
# trying to install nginx and update the cache in the same step fails on first run
- name: Update cache as a separate step
  apt:
    update_cache: yes

- name: Install latest nginx
  apt:
    name: nginx
    state: latest
  notify:
  - Restart nginx

- name: Install certbot as snap
  snap:
    name: certbot
    classic: yes

- name: Prepare certbot command
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Ensure nginx started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
